version: "3.7"

services:
  php-fpm:
    image: spec-pattern-php
    env_file:
      - "${ENV_FILE}"
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - .:/var/www/spec-pattern
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  db:
    image: mysql:8
    env_file:
      - "${ENV_FILE}"
#    environment:
#      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      MYSQL_DATABASE: "${MYSQL_DATABASE}"
#      MYSQL_USER: "${MYSQL_USER}"
#      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
#      MYSQL_HOST: "${MYSQL_HOST}"
    volumes:
      - ./docker/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - db-volume:/var/lib/mysql
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306"
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
#      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_ROOT_USER} -p ${MYSQL_ROOT_PASSWORD} -P ${MYSQL_EXPOSED_PORT}" ]
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "${MYSQL_HOST}", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-P${MYSQL_EXPOSED_PORT}" ]
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "${MYSQL_HOST}", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-P${MYSQL_EXPOSED_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db-volume:
