version: "3.7"

services:
  php-fpm:
#    container_name: spec-pattern-fpm
    #    image: spec-pattern-php
    env_file:
      - .env
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - .:/var/www/spec-pattern
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  db:
#    container_name: spec-pattern-db
    image: mysql:5.6
    env_file:
      - .env
    volumes:
      - ./docker/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - db-volume:/var/lib/mysql
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306"

volumes:
  db-volume:
